version: '2.4'
services: 
  rabbitmq:
    image: 'rabbitmq:3.8.14-management-alpine'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    restart: always

  redis-server:
    image: 'redis:latest'
    restart: always

  server:
    build: ./server
    # image: surendarsingh/compiler:server    
    environment:
      - AMQP_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis-server:6379
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    ports: 
      - "80:80"

  compiler:
    build: ./compiler
    # image: surendarsingh/compiler:compiler
    environment:
      - AMQP_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis-server:6379
    depends_on:
      - rabbitmq
      - redis-server
      - server
    restart: always
    pids_limit: 60
    cpus: 1
    mem_limit: 150M
    deploy:
      replicas: 1